image: Visual Studio 2026
#image: vs2026-master-gce-us-central1
#build_cloud: bakery-gce-us-central1


before_build:
- dotnet restore
- nuget restore
#- rd /s /q "C:\Program Files\dotnet\sdk\1.0.1"

test: off
